#!/usr/bin/env bash

set -exu

readonly BUILD_TARGETS="${1:-linux/arm/v7}"

# change this if we're pointing the _ucarp_ sources at a different commit.
# that is, we patched something that wasn't in .github/ or debian/
PKG_VERSION="1.5.2+git20260315.52e4b13"

# this number is more representative of when the build _ran_
PKG_BUILD_NUMBER="$(date '+%Y%m%d%H%M%S')"

DOCKER_PROGRESS='auto'
[[ "${CI:-}" ]] && DOCKER_PROGRESS='plain'

# determine if we need to update sources.tar
readarray -t FILES < <(git ls-files | grep -v '^\.')
out_tar="sources.tar"
build_tar=n
for file in "${FILES[@]}" ; do
  [[ "${file}" -nt "${out_tar}" ]] && build_tar=y
done
{ [[ ! -e "${out_tar}" ]] || [[ "${build_tar}" == "y" ]] ; } && tar --numeric-owner --group=0 --owner=0 -c -f "sources.tar" "${FILES[@]}"

# build in a docker container
DOCKER_BUILDKIT=1 docker buildx build \
  --file ./.github/packaging/Dockerfile \
  --platform "${BUILD_TARGETS}" \
  --build-arg PKG_VERSION="${PKG_VERSION}" \
  --build-arg PKG_BUILD_NUMBER="${PKG_BUILD_NUMBER}" \
  --target=artifact \
  --progress="${DOCKER_PROGRESS}" \
  --output "type=local,dest=$(pwd)/build/" \
  .
